# This workflow lists all images in the cloudinary upload folder
# & deletes older ones.

# Runs every monday @ 9am
name: Cloudinary Cleanup

on:
  schedule:
    - cron: "0 9 * * MON"
  # Enables manual run from the Actions tab in GH
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      SECRET_KEY: ${{ secrets.CLOUDINARY_API_SECRET_KEY }}
      CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
    steps:
      - name: Log encrypted env vars
        run: echo "$API_KEY -> $SECRET_KEY -> $CLOUD_NAME"
      - name: Curl url
        run: curl https://$API_KEY:$SECRET_KEY@api.cloudinary.com/v1_1/$CLOUD_NAME/folders
      - name: Retrieve files in cloudinary
        id: cloudinaryRequest
        uses: fjogeleit/http-request-action@master
        with:
          url: https://api.cloudinary.com/v1_1/$CLOUD_NAME/folders
          method: "GET"
          username: ${{ secrets.CLOUDINARY_API_KEY }}
          password: ${{ secrets.CLOUDINARY_API_SECRET_KEY }}
      - name: Log files from cloudinary
        run: echo "Images are ${{ toJSON(steps.cloudinaryRequest.outputs.response) }}"
