# This workflow lists all images in the cloudinary upload folder
# & deletes older ones.

# Runs every monday @ 9am
name: Cloudinary Cleanup

on:
  schedule:
    - cron: "0 9 * * MON"
  # Enables manual run from the Actions tab in GH
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log encrypted env vars
        run: echo "${{ secrets.CLOUDINARY_API_KEY }} -> ${{ secrets.CLOUDINARY_API_SECRET_KEY }} -> ${{ secrets.CLOUDINARY_CLOUD_NAME }}"
      - name: Retrieve files in cloudinary
        id: cloudinaryRequest
        uses: fjogeleit/http-request-action@master
        env:
          API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          SECRET_KEY: ${{ secrets.CLOUDINARY_API_SECRET_KEY }}
          CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        with:
          url: https://$API_KEY:$SECRET_KEY@api.cloudinary.com/v1_1/$CLOUD_NAME/folders
          method: "POST"
      - name: Log files from cloudinary
        run: echo "Images are ${{ toJSON(steps.cloudinaryRequest.outputs.response) }}"
